name: Validate/Test Files

on:
  workflow_dispatch: {}
  push: {}

jobs:
  python-lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Ruff Format
        uses: astral-sh/ruff-action@57714a7c8a2e59f32539362ba31877a1957dded1
        with:
          src: '.'
          args: 'format --check'
      - name: Ruff Check
        uses: astral-sh/ruff-action@57714a7c8a2e59f32539362ba31877a1957dded1
        with:
          src: '.'

      - name: setup python
        run: |
          curl https://mise.run | bash
          mise install
          eval "$(mise activate bash)"
          uv sync
          uv run
      - name: run mypy
        run: uv run mypy .

  markdown:
    name: Markdown linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Markdown linting
        uses: DavidAnson/markdownlint-cli2-action@992badcdf24e3b8eb7e87ff9287fe931bcb00c6e
        with:
          config: .markdownlint.json

  yamllint:
    name: Yaml Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: yaml lint
        uses: reviewdog/action-yamllint@f01d8a48fd8d89f89895499fca2cff09f9e9e8c0
        with:
          github_token: ${{ github.token }}
          reporter: github-pr-review
          fail_level: error
          level: info
          # we should consistently scan all files
          yamllint_flags: "-c .yamllint-config.yaml --no-warnings ."
