name: Validate/Test Files

on:
  workflow_dispatch: {}
  push: {}

jobs:
  python-lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Ruff Format
        uses: astral-sh/ruff-action@57714a7c8a2e59f32539362ba31877a1957dded1
        with:
          src: '.'
          args: 'format --check'
      - name: Ruff Check
        uses: astral-sh/ruff-action@57714a7c8a2e59f32539362ba31877a1957dded1
        with:
          src: '.'
