# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Validate/Test Files

on:
  workflow_dispatch: {}
  push: {}

jobs:
  python-lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup python
        run: |
          curl -SsL https://mise.run | bash > /dev/null
          mise trust --quiet .config/mise.toml
          mise install --quiet
          eval "$(mise activate bash)" > /dev/null
          pip install -q --no-cache-dir --upgrade pip wheel uv
          uv sync
      - name: Ruff Format
        run: |
          eval "$(mise activate bash)"
          uv run ruff format --check
      - name: Ruff Check
        run: |
          eval "$(mise activate bash)"
          uv run ruff check
      - name: run mypy
        run: |
          eval "$(mise activate bash)"
          uv run mypy .

  markdown:
    name: Markdown linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Markdown linting
        uses: DavidAnson/markdownlint-cli2-action@992badcdf24e3b8eb7e87ff9287fe931bcb00c6e
        with:
          config: .markdownlint.json

  yamllint:
    name: Yaml Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: yaml lint
        uses: reviewdog/action-yamllint@f01d8a48fd8d89f89895499fca2cff09f9e9e8c0
        with:
          github_token: ${{ github.token }}
          reporter: github-pr-review
          fail_level: error
          level: info
          # we should consistently scan all files
          yamllint_flags: "-c .yamllint-config.yaml --no-warnings ."
